version: "3.7"
services:
  app:
    build:
      args:
        user: admin
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    platform: linux/amd64
    image: banksystem-dev
    container_name: banksystem-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - banksystem

  nginx:
    platform: linux/amd64
    image: nginx:alpine
    container_name: banksystem-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - banksystem

networks:
  banksystem:
    driver: bridge
